### ISSUE TITLE
create XML file for campuses

### ISSUE THREAD

**Issue by valeri-psu-edu** [TTmkrebs/team3_final_project#10]
- [x] Shenango
- [x] Greater Allegheny
- [x] University Park
- [x] Worthington Scranton
- [x] Great Valley
- [x] World Campus

- [x] **use XML_240.java from [examples in lesson 11](https://psu.instructure.com/courses/1894370/pages/l11-the-xml-240-class-a-guide-and-example-for-the-final-project?module_item_id=23059878)** 

![campuspanellayout](https://user-images.githubusercontent.com/22803188/32866700-0ad4a680-ca37-11e7-96b5-76a004dcfaf6.png)

**Comment by TTmkrebs** [comment]
campusList.xml created using XML_240 and placed in project folder
