### ISSUE TITLE
design campus panel layout

### ISSUE THREAD

**Issue by valeri-psu-edu** [TTmkrebs/team3_final_project#11]
- [x] add inner panels
- [x] add back buttons
- [x] add listeners for back buttons
- [x] add label for instructions panel
- [ ] add "Playing As: " and character choice
- [ ] add character image
- [ ] add campus logos
- [ ] add timer display
- [ ] add campus background images

![campuspanellayout](https://user-images.githubusercontent.com/22803188/32866725-2c14cd0c-ca37-11e7-8174-51d06bbade62.png)

**Comment by TTmkrebs** [comment]
My demo Campus Panel with no graphics added:

`package team3_final_project;

import javax.swing.*;

public class Campus
{
    private String campusName;
    private int campusColor;
    private ImageIcon campusIcon;
    
    public Campus()
    {

    }
    
    public void setName(String name)
    {
        campusName = name;
    }
    
    public void setColor(int color)
    {
        campusColor = color;
    }
    
    public void setIcon(ImageIcon icon)
    {
        campusIcon = icon;
    }
    
    public String getName()
    {
        return campusName;
    }
    
    public int getColor()
    {
        return campusColor;
    }
    
    public ImageIcon getIcon()
    {
        return campusIcon;
    }
}`

Then in the main panel/frame, we add and call:

`public void createCampuses()
    {
        XML_240 xml = new XML_240();
        xml.openReaderXML("campusList.xml");
        
        Campus[] campusList = new Campus[6];
        
        for(int i = 0; i < 6; i++)
        {
            String name = (String)xml.ReadObject();
            int color = (int)xml.ReadObject();
            ImageIcon icon = (ImageIcon)xml.ReadObject();
            
            campusList[i] = new Campus();
            campusList[i].setName(name);
            campusList[i].setColor(color);
            campusList[i].setIcon(icon);
        }
    }`

**Comment by TTmkrebs** [comment]
added buttons for timer and score - brought theme into appropriate box
