### ISSUE TITLE
implement character movement 

### ISSUE THREAD

**Issue by valeri-psu-edu** [TTmkrebs/team3_final_project#12]
- [x] cursor/character image moves across map
- [x] game enters specific campus when cursor reaches campus on map
- [x] cursor remains on last campus entered when back button is hit from campus panel

**Comment by valeri-psu-edu** [comment]
I've added rectangles to the map image to give us a "close enough" range for character movement. Opening the image in Window's Paint can give you the pixel coordinates of each.

**Comment by valeri-psu-edu** [comment]
We need to do something so that when the user goes back to the campus map panel, whether because they've finished the mini game or because they hit the button to do so, the cursor doesn't just keep entering the same campus. According to the rules of the game, the game is over when the user has interacted with 5 campuses. Doesn't say they have to complete the challenge at each, just go to each. So we could either make the visited campuses inaccessible after the return, or we could maybe offset the cursor a bit from where it was. It's supposed to be in the same position though, so I'm guessing we should be "turning off" the campuses as the user visits them. Another possible option is to tighten the window that opens the campuses. This would work as a short-term fix probably.

**Comment by TTmkrebs** [comment]
I have a boolean value in the campus whether it's completed or not.  Once the game has been played, we can toggle this off and the campus won't be able to be entered again.
