### ISSUE TITLE
tic tac toe game not visible

### ISSUE THREAD

**Issue by valeri-psu-edu** [TTmkrebs/team3_final_project#32]
code for the game itself appears intact, but actual game isn't showing up

- [x] eventually we should move the code for the tic tac toe game to a separate panel and import it. perhaps one panel with all the games in it?

**Comment by TTmkrebs** [comment]
Alright - that's fine.  For now I've added it to the panel.  If that's the case, we'll need to change the way the panel for the game area is created.

**Comment by TTmkrebs** [comment]
Extracted game into it's own panel and implemented.
