### ISSUE TITLE
ask prof about extra options (like difficulty) and UML diagrams

### ISSUE THREAD

**Issue by valeri-psu-edu** [TTmkrebs/team3_final_project#40]
Just let us know what he says here

**Comment by alyssa-psu** [comment]
"Hi Alyssa. First, for the rubric, what differences are you seeing between the two versions? I havn't taken a close look at that yet.

Inclusion of the UML diagram should not have been part of the assignment, so you can ignore that.

Using three characters and three theme options sounds fine. I think that step needs to be clarified or re-written in some way, but at this late date, it's fine to move ahead with three characters and three theme options. 

Does that resolve the questions you had? Thanks.

-Dr. Choman"
